//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_MovimientosAuxiliares
    {
        public string Cia { get; set; }
        public System.DateTime FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public string CuentaCont { get; set; }
        public string CodClteApls { get; set; }
        public System.DateTime FecMovAux { get; set; }
        public string TipoDocAux { get; set; }
        public string NumDocAux { get; set; }
        public byte MovAux { get; set; }
        public System.DateTime FecMovAplicAux { get; set; }
        public string TipoDocMovAplicAux { get; set; }
        public string NumDocMovAplicAux { get; set; }
        public decimal ValorDebMovAux { get; set; }
        public decimal ValorCreMovAux { get; set; }
        public string DetalleMovAux { get; set; }
        public string AplicPagosPrest { get; set; }
        public bool Proceso { get; set; }
        public Nullable<System.DateTime> FechaProcesado { get; set; }
    }
}
