//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNT_MovimientosContabilidad
    {
        public string Cia { get; set; }
        public Nullable<System.DateTime> FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public string CuentaCont { get; set; }
        public System.DateTime FechaDocCont { get; set; }
        public string TipoDocCont { get; set; }
        public string NumDocCont { get; set; }
        public byte MovPartCont { get; set; }
        public decimal ValorDebPartCont { get; set; }
        public decimal ValorCrePartCont { get; set; }
        public string ObservPartCont { get; set; }
        public string AplicPagosPrest { get; set; }
        public bool Proceso { get; set; }
        public Nullable<System.DateTime> FechaProcesado { get; set; }
    }
}
