//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNT_MaestroPresupuestoContabilidad
    {
        public string Cia { get; set; }
        public Nullable<System.DateTime> FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public string Año { get; set; }
        public string CuentaCont { get; set; }
        public Nullable<decimal> Pre_Enero { get; set; }
        public Nullable<decimal> Pre_Febrero { get; set; }
        public Nullable<decimal> Pre_Marzo { get; set; }
        public Nullable<decimal> Pre_Abril { get; set; }
        public Nullable<decimal> Pre_Mayo { get; set; }
        public Nullable<decimal> Pre_Junio { get; set; }
        public Nullable<decimal> Pre_Julio { get; set; }
        public Nullable<decimal> Pre_Agosto { get; set; }
        public Nullable<decimal> Pre_Septiembre { get; set; }
        public Nullable<decimal> Pre_Octubre { get; set; }
        public Nullable<decimal> Pre_Noviembre { get; set; }
        public Nullable<decimal> Pre_Diciembre { get; set; }
        public bool Proceso { get; set; }
        public Nullable<System.DateTime> FechaProcesado { get; set; }
    }
}
