//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRL_TipoDocumento
    {
        public string Cia { get; set; }
        public Nullable<System.DateTime> FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public string IDTipoDoc { get; set; }
        public string Descripcion { get; set; }
        public string NCF { get; set; }
        public string SecuenciaNCF { get; set; }
        public string Secuencia { get; set; }
        public string PreSecuencia { get; set; }
        public Nullable<byte> SiCargo { get; set; }
        public string Almacen { get; set; }
    }
}
