//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRL_Parametros
    {
        public string Cia { get; set; }
        public Nullable<System.DateTime> FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public int ID { get; set; }
        public string SecuenciaRc { get; set; }
        public string CampoControl { get; set; }
        public Nullable<System.DateTime> Fecha_ult_Mayor { get; set; }
        public string PrefijoCtaActivos { get; set; }
        public string PrefijoCtaCostos { get; set; }
        public string PreFijoCtaIngresos { get; set; }
        public string PrefijoCtaGastos { get; set; }
        public string CuentaResultado { get; set; }
        public Nullable<byte> LONGITUD { get; set; }
        public string SEPARADOR { get; set; }
        public string PREFIJO_LARGAD { get; set; }
        public Nullable<int> Itbis { get; set; }
        public string MascaraCuentas { get; set; }
        public Nullable<int> Marque { get; set; }
        public Nullable<int> SobreGiro { get; set; }
        public Nullable<int> TipoCheque { get; set; }
        public Nullable<int> TipoRecibo { get; set; }
        public Nullable<System.DateTime> FechaUltCInv { get; set; }
        public Nullable<System.DateTime> FechaUltCActivos { get; set; }
        public Nullable<System.DateTime> FechaUltimaPosicion { get; set; }
        public Nullable<System.DateTime> FechaUltAuxiliar { get; set; }
        public Nullable<int> super { get; set; }
        public Nullable<int> certi { get; set; }
        public string ruta { get; set; }
        public string CxC { get; set; }
        public string CxP { get; set; }
        public string Prestamo { get; set; }
        public string cuentacaja { get; set; }
        public string DescuentoCxC { get; set; }
        public string DescuentoCxP { get; set; }
        public string ActualizaCondeCxC { get; set; }
        public string ActualizaCondeCxP { get; set; }
        public Nullable<System.DateTime> FechaCierreCxC { get; set; }
        public Nullable<int> conItbis { get; set; }
        public string ActualizaInvaCxP { get; set; }
        public string IdInv { get; set; }
        public Nullable<decimal> DIFERENCIA { get; set; }
        public Nullable<int> Regulada { get; set; }
        public Nullable<int> PrecioDeVentaITBISNoSi { get; set; }
        public Nullable<int> CostoConITBISNoSi { get; set; }
        public string EmiteRcCont { get; set; }
        public string CodificaRcCont { get; set; }
        public string EmiteFt { get; set; }
        public string ModificaFT { get; set; }
        public string ApruebaCredito { get; set; }
        public string ApruebaCreditoconAtraso { get; set; }
        public string ApruebaMora { get; set; }
        public string PorcientoMora { get; set; }
        public string EmiteRcCXC { get; set; }
        public string EmiteSolicitudChk { get; set; }
        public string CodificaSolicitudChk { get; set; }
        public string RevisarSolicitudChk { get; set; }
        public string ApruebasolicitudChk { get; set; }
        public Nullable<int> CantidadCia { get; set; }
        public Nullable<double> PorIncrementoActivo { get; set; }
        public string CuantaDeVoluciones { get; set; }
        public string CuentaDeDVSinCargoEnCXC { get; set; }
        public string CuentaFuncionarioEmp { get; set; }
        public string RealizarDescuento { get; set; }
        public string BajaPrecio { get; set; }
        public string PrecioXdeBajoCosto { get; set; }
        public string CuentaCartera { get; set; }
        public string CInteres { get; set; }
        public string cComision { get; set; }
        public string cComisionVenta { get; set; }
        public string cMora { get; set; }
        public string cCaja { get; set; }
        public string cAdjudicado { get; set; }
        public string NoCobrable { get; set; }
        public string CuentaAuxiliarPr { get; set; }
        public string cOtros { get; set; }
        public string cAdministrativo { get; set; }
        public string cLegal { get; set; }
        public string cSeguro { get; set; }
        public string cExoneracion { get; set; }
        public string cTraspaso { get; set; }
        public string cRegistro { get; set; }
        public string cInteresCXC { get; set; }
        public string cComisionesCXC { get; set; }
        public string cInteresAnt { get; set; }
        public string cComisionesAnt { get; set; }
        public bool GridComisiones { get; set; }
        public bool GridComisionVenta { get; set; }
        public bool GridRegistro { get; set; }
        public bool GridSeguro { get; set; }
        public bool GridExoneracion { get; set; }
        public bool GridLegal { get; set; }
        public bool GridOtros { get; set; }
        public bool GridTraspaso { get; set; }
        public bool GridCalculo { get; set; }
        public string ApruebaNotaCredito { get; set; }
        public string RealizaCambioTasaCer { get; set; }
        public string RealizaRetiroInt { get; set; }
        public Nullable<System.DateTime> FechaCierreCer { get; set; }
        public Nullable<System.DateTime> FechaCalculoCer { get; set; }
        public string CuentaInteresCertificado { get; set; }
        public string CuentaCapitalsCertificado1 { get; set; }
        public string CuentaCapitalsCertificado2 { get; set; }
        public string DigitaSolicitudPr { get; set; }
        public string RevisaSolicitudPr { get; set; }
        public string ApruebaSolicitudPr { get; set; }
        public string ApruebaDesembolsoPr { get; set; }
        public string ApruebaDesembolsoPrPrestamo { get; set; }
        public string DepuradoPorPr { get; set; }
        public string VerificadoDomPr { get; set; }
        public string AnalizadoPr { get; set; }
        public string ApruebaCalculoInteresDevengado { get; set; }
        public Nullable<bool> gGestionFinanciera { get; set; }
        public string AnularPrestamo { get; set; }
        public string AutorizaNcyPagoSoloCapital { get; set; }
        public System.DateTime FechaControlMasAntigua { get; set; }
    }
}
