//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRL_NCFNULO
    {
        public string Cia { get; set; }
        public System.DateTime FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public string Documento { get; set; }
        public string TipoDocumento { get; set; }
        public System.DateTime FechaDocumento { get; set; }
        public string NCF { get; set; }
    }
}
