//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HST_MaestroCuenta
    {
        public string Cia { get; set; }
        public Nullable<System.DateTime> FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public string CuentaCont { get; set; }
        public string CuentaControl { get; set; }
        public string DesCuentaCont { get; set; }
        public Nullable<System.DateTime> FecAperCtaCont { get; set; }
        public Nullable<byte> OrigenCuenta { get; set; }
        public Nullable<byte> AceptaMov { get; set; }
        public string TieneAux { get; set; }
        public Nullable<decimal> BceCuentaCont { get; set; }
        public Nullable<decimal> ValorDebCont { get; set; }
        public decimal ValorCreCont { get; set; }
        public Nullable<decimal> BceEneCont { get; set; }
        public Nullable<decimal> BceFebCont { get; set; }
        public Nullable<decimal> BceMarCont { get; set; }
        public Nullable<decimal> BceAbrCont { get; set; }
        public Nullable<decimal> BceMayCont { get; set; }
        public Nullable<decimal> BceJunCont { get; set; }
        public Nullable<decimal> BceJulCont { get; set; }
        public Nullable<decimal> BceAgoCont { get; set; }
        public Nullable<decimal> BceSepCont { get; set; }
        public Nullable<decimal> BceOctCont { get; set; }
        public Nullable<decimal> BceNovCont { get; set; }
        public Nullable<decimal> BceDicCont { get; set; }
        public Nullable<decimal> Bce13Cont { get; set; }
        public Nullable<byte> Analitico { get; set; }
        public string Periodo { get; set; }
        public Nullable<int> Mes { get; set; }
    }
}
