//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroRc
    {
        public string Cia { get; set; }
        public Nullable<System.DateTime> FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public string NumeroRc { get; set; }
        public System.DateTime FechaRc { get; set; }
        public string Beneficiario { get; set; }
        public string Detalle { get; set; }
        public string RealizadoPor { get; set; }
        public Nullable<decimal> TotalRc { get; set; }
        public Nullable<decimal> ValorEfectivo { get; set; }
        public string EstatusRc { get; set; }
        public Nullable<System.DateTime> FecActContRc { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> DeFecha { get; set; }
        public string Banco { get; set; }
        public string Cuentadebanco { get; set; }
        public string CodigoMoneda { get; set; }
        public string Almacen { get; set; }
        public string TipoDocCont { get; set; }
        public Nullable<int> TipoNCF { get; set; }
        public string NCF { get; set; }
        public string RNC { get; set; }
        public string DescripcionNCF { get; set; }
        public Nullable<int> IDOperacionSIB { get; set; }
    }
}
