//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestraNCF
    {
        public string Cia { get; set; }
        public Nullable<System.DateTime> FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public string TipoDoc { get; set; }
        public string NCF { get; set; }
        public double OrdenNCF { get; set; }
        public string DescripcionNCF { get; set; }
        public string Minimo { get; set; }
        public string Maximo { get; set; }
        public string Secuencia { get; set; }
        public string Activo { get; set; }
    }
}
