//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTC_MaestroCias
    {
        public string CodigoCia { get; set; }
        public System.DateTime FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public string NombreCia { get; set; }
        public string NombreClte { get; set; }
        public string ApellidoClte { get; set; }
        public string DireccionCia { get; set; }
        public string CiudadCia { get; set; }
        public string SectorCia { get; set; }
        public string PaisCia { get; set; }
        public string ProvinciaCia { get; set; }
        public string RncCia { get; set; }
        public string RegistroMercantilCia { get; set; }
        public string TelefonosCia { get; set; }
        public string FaxCia { get; set; }
        public string EmailCia { get; set; }
        public string WebCia { get; set; }
        public string LocalNo { get; set; }
        public Nullable<byte> Consolidacion { get; set; }
        public byte[] LogoCia { get; set; }
    }
}
