//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTC_rptCalculoMoraPrestamo
    {
        public string Cia { get; set; }
        public Nullable<System.DateTime> FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public string Cuota { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Valor { get; set; }
        public string Dias { get; set; }
        public decimal Calculo { get; set; }
        public string TasaAnual { get; set; }
        public string PC { get; set; }
    }
}
