//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTC_tmpReporteInteresComision
    {
        public string Cia { get; set; }
        public Nullable<System.DateTime> FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public string Prestmos { get; set; }
        public string Nombre { get; set; }
        public decimal Balance { get; set; }
        public decimal Interes { get; set; }
        public decimal Comision { get; set; }
        public decimal Otros { get; set; }
        public int CuotaVenc { get; set; }
        public int DiasVenc { get; set; }
        public decimal Mora { get; set; }
        public decimal Total { get; set; }
        public string PC { get; set; }
    }
}
