//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTC_ProgramasPorUsuarios
    {
        public string Cia { get; set; }
        public Nullable<System.DateTime> FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public string IdentificacionUsr { get; set; }
        public string CodigoApls { get; set; }
        public string NombreFrm { get; set; }
        public Nullable<byte> TodoTipoAccesUsrpgms { get; set; }
        public Nullable<byte> EscribirUsrpgms { get; set; }
        public Nullable<byte> LeerUsrpgms { get; set; }
        public Nullable<byte> ModificarUsrpgms { get; set; }
        public Nullable<byte> EliminarUsrpgms { get; set; }
    }
}
