//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTC_MaestroAplicaciones
    {
        public string Cia { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> FechaHoraReg { get; set; }
        public string CodigoApls { get; set; }
        public string DescripcionApls { get; set; }
        public Nullable<int> OrdenApls { get; set; }
        public string Grupo { get; set; }
        public Nullable<int> IdIcon { get; set; }
    }
}
