//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTC_CobrosRealizadosOffline
    {
        public string Cia { get; set; }
        public Nullable<System.DateTime> FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public string NoTransaccion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string CodigoCobrador { get; set; }
        public string Contrato { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<decimal> Capital { get; set; }
        public Nullable<decimal> Interes { get; set; }
        public Nullable<decimal> Comision { get; set; }
        public Nullable<decimal> Otros { get; set; }
        public Nullable<decimal> IntAdicional { get; set; }
        public Nullable<decimal> Auxiliar { get; set; }
        public Nullable<decimal> Mora { get; set; }
        public string Moneda { get; set; }
        public string DescripcionMoneda { get; set; }
        public string ConceptoDelPago { get; set; }
        public string NombreDispositivoMovil { get; set; }
        public string NombreCompañia { get; set; }
    }
}
