//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTC_rptCuotasVencidasYNoSaldadas
    {
        public string Cia { get; set; }
        public Nullable<System.DateTime> FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public string CodigoCliente { get; set; }
        public string Contrato { get; set; }
        public string Cuotas { get; set; }
        public decimal Capital { get; set; }
        public decimal Interes { get; set; }
        public decimal Comision { get; set; }
        public decimal ComisionVenta { get; set; }
        public decimal Traspaso { get; set; }
        public decimal Registro { get; set; }
        public decimal Seguro { get; set; }
        public decimal Exoneracion { get; set; }
        public decimal Legal { get; set; }
        public decimal Otros { get; set; }
        public decimal Total { get; set; }
        public System.DateTime FechaCuotas { get; set; }
        public string PC { get; set; }
    }
}
