//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTC_PagosDePrestamo
    {
        public string Cia { get; set; }
        public Nullable<System.DateTime> FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public string Contrato { get; set; }
        public System.DateTime FechaDocCont { get; set; }
        public string TipoDocCont { get; set; }
        public string NumDocCont { get; set; }
        public byte MovDocCont { get; set; }
        public Nullable<decimal> TasayOtros { get; set; }
        public string CodigoCobrador { get; set; }
        public Nullable<decimal> ValorPagoCapital { get; set; }
        public Nullable<decimal> ValorPagoInteres { get; set; }
        public Nullable<decimal> ValorPagoComision { get; set; }
        public Nullable<decimal> ValorPagoComisionVenta { get; set; }
        public Nullable<decimal> ValorPagoMora { get; set; }
        public Nullable<decimal> ValorPagoTraspaso { get; set; }
        public Nullable<decimal> ValorPagoRegistro { get; set; }
        public Nullable<decimal> ValorPagoSeguro { get; set; }
        public Nullable<decimal> ValorPagoExoneracion { get; set; }
        public Nullable<decimal> ValorPagoLegal { get; set; }
        public Nullable<decimal> ValorPagoOtros { get; set; }
        public string NCF { get; set; }
        public string NoTransaccion { get; set; }
    }
}
