//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTC_CuotasDePrestamo
    {
        public string Cia { get; set; }
        public Nullable<System.DateTime> FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public string Contrato { get; set; }
        public string CuotaNumPtm { get; set; }
        public System.DateTime FechaVencCuota { get; set; }
        public Nullable<decimal> ValorCuotaCap { get; set; }
        public Nullable<decimal> ValorCuotaInt { get; set; }
        public Nullable<decimal> ValorCuotaCom { get; set; }
        public Nullable<decimal> ValorCuotaComVta { get; set; }
        public Nullable<decimal> ValorCuotaTrasp { get; set; }
        public Nullable<decimal> ValorCuotaReg { get; set; }
        public Nullable<decimal> ValorCuotaSeg { get; set; }
        public Nullable<decimal> ValorCuotaExo { get; set; }
        public Nullable<decimal> ValorCuotaLegal { get; set; }
        public Nullable<decimal> ValorCuotaOtros { get; set; }
    }
}
