//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaParagit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciboCodificado
    {
        public string Cia { get; set; }
        public System.DateTime FechaHoraReg { get; set; }
        public string Usuario { get; set; }
        public string NumeroRc { get; set; }
        public byte Movimiento { get; set; }
        public string CuentaCont { get; set; }
        public string CodigoAux { get; set; }
        public System.DateTime Fecmovaux { get; set; }
        public System.DateTime FecMovAplicAux { get; set; }
        public string TipoDocMovAplicAux { get; set; }
        public string NumDocMovAplicAux { get; set; }
        public string AplicPrestamo { get; set; }
        public string DetalleAux { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Almacen { get; set; }
        public string TipoDocCont { get; set; }
    }
}
